const books = [
  {
    Title: "The Great Gatsby",
    Author: "F. Scott Fitzgerald",
    CoverArt: "gatsby.jpg",
    PublishingHouse: "Charles Scribner's Sons",
    ReleaseDate: "1925-04-10",
    Genre: ["Fiction"],
    Amount: 1,
  },
  {
    Title: "To Kill a Mockingbird",
    Author: "Harper Lee",
    CoverArt: "mockingbird.jpg",
    PublishingHouse: "J. B. Lippincott & Co.",
    ReleaseDate: "1960-07-11",
    Genre: ["Fiction"],
    Amount: 2,
  },
  {
    Title: "1984",
    Author: "George Orwell",
    CoverArt: "1984.jpg",
    PublishingHouse: "Secker & Warburg",
    ReleaseDate: "1949-06-08",
    Genre: ["Dystopian", "Fiction"],
    Amount: 3,
  },
  {
    Title: "The Catcher in the Rye",
    Author: "J. D. Salinger",
    CoverArt: "catcher.jpg",
    PublishingHouse: "Little, Brown and Company",
    ReleaseDate: "1951-07-16",
    Genre: ["Fiction"],
    Amount: 4,
  },
  {
    Title: "Pride and Prejudice",
    Author: "Jane Austen",
    CoverArt: "pride.jpg",
    PublishingHouse: "T. Egerton, Whitehall",
    ReleaseDate: "1813-01-28",
    Genre: ["Romance", "Fiction"],
    Amount: 5,
  },
  {
    Title: "Harry Potter and the Philosopher's Stone",
    Author: "J.K. Rowling",
    CoverArt: "harry_potter.jpg",
    PublishingHouse: "Bloomsbury",
    ReleaseDate: "1997-06-26",
    Genre: ["Fantasy", "Fiction"],
    Amount: 6,
  },
  {
    Title: "The Lord of the Rings",
    Author: "J.R.R. Tolkien",
    CoverArt: "lotr.jpg",
    PublishingHouse: "Allen & Unwin",
    ReleaseDate: "1954-07-29",
    Genre: ["Fantasy"],
    Amount: 7,
  },
  {
    Title: "The Hobbit",
    Author: "J.R.R. Tolkien",
    CoverArt: "hobbit.jpg",
    PublishingHouse: "Allen & Unwin",
    ReleaseDate: "1937-09-21",
    Genre: ["Fantasy"],
    Amount: 8,
  },
  {
    Title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    Author: "C.S. Lewis",
    CoverArt: "narnia.jpg",
    PublishingHouse: "Geoffrey Bles",
    ReleaseDate: "1950-10-16",
    Genre: ["Fantasy"],
    Amount: 9,
  },
  {
    Title: "The Da Vinci Code",
    Author: "Dan Brown",
    CoverArt: "davinci.jpg",
    PublishingHouse: "Doubleday",
    ReleaseDate: "2003-03-18",
    Genre: ["Mystery", "Thriller"],
    Amount: 10,
  },
  {
    Title: "Les Misérables",
    Author: "Victor Hugo",
    CoverArt: "les_miserables.jpg",
    PublishingHouse: "A. Lacroix, Verboeckhoven & Cie.",
    ReleaseDate: "1862-03-04",
    Genre: ["Historical", "Fiction"],
    Amount: 1,
  },
  {
    Title: "Der Steppenwolf",
    Author: "Hermann Hesse",
    CoverArt: "steppenwolf.jpg",
    PublishingHouse: "S. Fischer Verlag",
    ReleaseDate: "1927-10-05",
    Genre: ["Philosophical", "Fiction"],
    Amount: 2,
  },
  {
    Title: "Il nome della rosa",
    Author: "Umberto Eco",
    CoverArt: "nome_della_rosa.jpg",
    PublishingHouse: "Bompiani",
    ReleaseDate: "1980-10-16",
    Genre: ["Historical", "Mystery"],
    Amount: 3,
  },
  {
    Title: "Les Trois Mousquetaires",
    Author: "Alexandre Dumas",
    CoverArt: "trois_mousquetaires.jpg",
    PublishingHouse: "Baudry",
    ReleaseDate: "1844-03-14",
    Genre: ["Historical", "Adventure"],
    Amount: 5,
  },
  {
    Title: "Der Process",
    Author: "Franz Kafka",
    CoverArt: "der_process.jpg",
    PublishingHouse: "Kurt Wolff Verlag",
    ReleaseDate: "1925-04-26",
    Genre: ["Existential", "Fiction"],
    Amount: 6,
  },
  {
    Title: "I Promessi Sposi",
    Author: "Alessandro Manzoni",
    CoverArt: "promessi_sposi.jpg",
    PublishingHouse: "Stamperia di Paolo Andrea Molina",
    ReleaseDate: "1827-07-15",
    Genre: ["Historical", "Romance"],
    Amount: 7,
  },
  {
    Title: "Gospoda Glembajevi",
    Author: "Miroslav Krleža",
    CoverArt: "glembajevi.jpg",
    PublishingHouse: "Zora",
    ReleaseDate: "1928-12-01",
    Genre: ["Drama"],
    Amount: 8,
  },
  {
    Title: "Le Petit Prince",
    Author: "Antoine de Saint-Exupéry",
    CoverArt: "petit_prince.jpg",
    PublishingHouse: "Reynal & Hitchcock",
    ReleaseDate: "1943-04-06",
    Genre: ["Philosophical", "Fiction"],
    Amount: 9,
  },
];

export default books;
